;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-append-line
	evil-backward-char
	evil-digit-argument-or-evil-beginning-of-line
	evil-end-of-line
	evil-forward-char
	evil-insert
	evil-insert-line
	evil-next-line
	evil-normal-state
	evil-previous-line
	))

(setq mc/cmds-to-run-once
      '(
	))
